MODEL_COLUMNS = [
    'latitude',
    'longitude',
    'floor',
    'total_floors',
    'rooms',
    'square',
    'year_built',
    'building_type',
    'residential_complex_name',
    'bathroom',
    'former_hostel',
    'analog_prices_median',
    'analog_prices_max',
    'analog_prices_min',
]
